import { FileItem, AuditEntry, ComplianceStat, TeamDrive, Notification, User } from './types';

export const currentUser: User = {
  name: 'Michael Schulz',
  email: 'michael@knightdivision.com',
  role: 'Chief Executive Officer',
  avatar: 'MS',
  clearanceLevel: 'SECRET',
};

export const mockFiles: FileItem[] = [
  {
    id: 'f1',
    name: 'Operations',
    type: 'folder',
    classification: 'CONFIDENTIAL',
    modified: '2026-04-06T14:30:00Z',
    created: '2025-11-01T09:00:00Z',
    owner: 'Michael Schulz',
    shared: true,
    starred: true,
    encrypted: true,
    signed: false,
    tags: ['operations', 'core'],
    versions: 1,
    children: [],
  },
  {
    id: 'f2',
    name: 'Contracts & Legal',
    type: 'folder',
    classification: 'CONFIDENTIAL',
    modified: '2026-04-05T10:00:00Z',
    created: '2025-10-15T08:00:00Z',
    owner: 'Matthew McCalla',
    shared: true,
    starred: false,
    encrypted: true,
    signed: false,
    tags: ['legal', 'contracts'],
    versions: 1,
  },
  {
    id: 'f3',
    name: 'Training & SOPs',
    type: 'folder',
    classification: 'CUI',
    modified: '2026-04-04T16:20:00Z',
    created: '2025-12-01T10:00:00Z',
    owner: 'Michael Schulz',
    shared: true,
    starred: false,
    encrypted: false,
    signed: false,
    tags: ['training', 'sop'],
    versions: 1,
  },
  {
    id: 'f4',
    name: 'Intelligence Briefs',
    type: 'folder',
    classification: 'SECRET',
    modified: '2026-04-06T08:45:00Z',
    created: '2026-01-10T07:00:00Z',
    owner: 'Michael Schulz',
    shared: false,
    starred: true,
    encrypted: true,
    signed: false,
    tags: ['intel', 'classified'],
    versions: 1,
  },
  {
    id: 'f5',
    name: 'Human Resources',
    type: 'folder',
    classification: 'CUI',
    modified: '2026-04-03T11:00:00Z',
    created: '2025-09-20T09:00:00Z',
    owner: 'Sarah Chen',
    shared: true,
    starred: false,
    encrypted: true,
    signed: false,
    tags: ['hr', 'personnel'],
    versions: 1,
  },
  {
    id: 'd1',
    name: 'Q2 2026 Strategic Operations Plan.pdf',
    type: 'pdf',
    classification: 'SECRET',
    size: 4200000,
    modified: '2026-04-06T12:00:00Z',
    created: '2026-03-28T14:00:00Z',
    owner: 'Michael Schulz',
    shared: false,
    starred: true,
    encrypted: true,
    signed: true,
    retentionDays: 2555,
    tags: ['strategy', 'Q2', 'operations'],
    versions: 4,
    approvalStatus: 'approved',
  },
  {
    id: 'd2',
    name: 'KDT Master Services Agreement - Template.docx',
    type: 'document',
    classification: 'CONFIDENTIAL',
    size: 890000,
    modified: '2026-04-05T09:15:00Z',
    created: '2025-11-20T10:00:00Z',
    owner: 'Matthew McCalla',
    shared: true,
    starred: false,
    encrypted: true,
    signed: true,
    retentionDays: 3650,
    tags: ['contract', 'template', 'legal'],
    versions: 12,
    approvalStatus: 'approved',
  },
  {
    id: 'd3',
    name: 'Personnel Security Clearance Tracker.xlsx',
    type: 'spreadsheet',
    classification: 'SECRET',
    size: 1200000,
    modified: '2026-04-06T15:00:00Z',
    created: '2025-08-01T08:00:00Z',
    owner: 'Sarah Chen',
    shared: true,
    starred: false,
    encrypted: true,
    signed: false,
    retentionDays: 1825,
    tags: ['personnel', 'clearance', 'security'],
    versions: 28,
    dlpFlag: true,
  },
  {
    id: 'd4',
    name: 'Field Operations SOP v3.2.pdf',
    type: 'pdf',
    classification: 'CUI',
    size: 6700000,
    modified: '2026-03-20T14:30:00Z',
    created: '2025-06-15T09:00:00Z',
    owner: 'James Rodriguez',
    shared: true,
    starred: true,
    encrypted: false,
    signed: true,
    retentionDays: 1095,
    tags: ['sop', 'field-ops', 'procedures'],
    versions: 7,
    approvalStatus: 'approved',
  },
  {
    id: 'd5',
    name: 'Threat Assessment Report - March 2026.pdf',
    type: 'pdf',
    classification: 'SECRET',
    size: 2100000,
    modified: '2026-04-01T11:00:00Z',
    created: '2026-03-31T16:00:00Z',
    owner: 'Michael Schulz',
    shared: false,
    starred: false,
    encrypted: true,
    signed: true,
    retentionDays: 730,
    tags: ['intel', 'threat-assessment', 'monthly'],
    versions: 2,
    approvalStatus: 'approved',
  },
  {
    id: 'd6',
    name: 'KDT Super App - Architecture Overview.pptx',
    type: 'presentation',
    classification: 'CUI',
    size: 15400000,
    modified: '2026-04-04T17:00:00Z',
    created: '2026-02-10T10:00:00Z',
    owner: 'Michael Schulz',
    shared: true,
    starred: true,
    encrypted: false,
    signed: false,
    tags: ['superapp', 'architecture', 'tech'],
    versions: 9,
  },
  {
    id: 'd7',
    name: 'Vehicle Fleet Maintenance Log.xlsx',
    type: 'spreadsheet',
    classification: 'UNCLASSIFIED',
    size: 340000,
    modified: '2026-04-06T09:30:00Z',
    created: '2025-07-01T08:00:00Z',
    owner: 'James Rodriguez',
    shared: true,
    starred: false,
    encrypted: false,
    signed: false,
    tags: ['logistics', 'fleet', 'maintenance'],
    versions: 45,
  },
  {
    id: 'd8',
    name: 'Client Onboarding Checklist.docx',
    type: 'document',
    classification: 'CUI',
    size: 230000,
    modified: '2026-03-25T13:00:00Z',
    created: '2025-10-05T11:00:00Z',
    owner: 'Matthew McCalla',
    shared: true,
    starred: false,
    encrypted: false,
    signed: false,
    tags: ['client', 'onboarding', 'checklist'],
    versions: 6,
  },
  {
    id: 'd9',
    name: 'Incident Response Protocol.pdf',
    type: 'pdf',
    classification: 'CONFIDENTIAL',
    size: 1800000,
    modified: '2026-02-14T10:00:00Z',
    created: '2025-05-22T09:00:00Z',
    owner: 'Sarah Chen',
    shared: true,
    starred: false,
    encrypted: true,
    signed: true,
    retentionDays: 2190,
    tags: ['incident', 'response', 'protocol', 'security'],
    versions: 5,
    approvalStatus: 'approved',
  },
  {
    id: 'd10',
    name: 'Quarterly Financial Report Q1-2026.xlsx',
    type: 'spreadsheet',
    classification: 'CONFIDENTIAL',
    size: 2800000,
    modified: '2026-04-02T16:00:00Z',
    created: '2026-04-01T08:00:00Z',
    owner: 'Matthew McCalla',
    shared: false,
    starred: false,
    encrypted: true,
    signed: false,
    retentionDays: 2555,
    tags: ['financial', 'quarterly', 'report'],
    versions: 3,
    dlpFlag: true,
  },
  {
    id: 'd11',
    name: 'Equipment Inventory - Q2 Audit.xlsx',
    type: 'spreadsheet',
    classification: 'CUI',
    size: 980000,
    modified: '2026-04-05T14:00:00Z',
    created: '2026-03-15T09:00:00Z',
    owner: 'James Rodriguez',
    shared: true,
    starred: false,
    encrypted: false,
    signed: false,
    tags: ['equipment', 'inventory', 'audit'],
    versions: 2,
  },
  {
    id: 'd12',
    name: 'Comms Plan - Operation Nightfall.pdf',
    type: 'pdf',
    classification: 'SECRET',
    size: 560000,
    modified: '2026-04-06T07:00:00Z',
    created: '2026-04-05T22:00:00Z',
    owner: 'Michael Schulz',
    shared: false,
    starred: true,
    encrypted: true,
    signed: true,
    retentionDays: 365,
    tags: ['comms', 'operation', 'nightfall'],
    versions: 1,
    approvalStatus: 'pending',
  },
  {
    id: 'd13',
    name: 'New Hire Training Schedule 2026.docx',
    type: 'document',
    classification: 'UNCLASSIFIED',
    size: 125000,
    modified: '2026-03-10T11:00:00Z',
    created: '2026-01-05T09:00:00Z',
    owner: 'Sarah Chen',
    shared: true,
    starred: false,
    encrypted: false,
    signed: false,
    tags: ['training', 'hr', 'schedule'],
    versions: 4,
  },
  {
    id: 'img1',
    name: 'Site Survey Photos - Facility Alpha.zip',
    type: 'archive',
    classification: 'CONFIDENTIAL',
    size: 89000000,
    modified: '2026-03-28T15:00:00Z',
    created: '2026-03-27T12:00:00Z',
    owner: 'James Rodriguez',
    shared: true,
    starred: false,
    encrypted: true,
    signed: false,
    tags: ['site-survey', 'photos', 'facility'],
    versions: 1,
  },
];

export const mockAuditLog: AuditEntry[] = [
  {
    id: 'a1',
    timestamp: '2026-04-06T16:28:00Z',
    user: 'Michael Schulz',
    userRole: 'CEO',
    action: 'viewed',
    target: 'Q2 2026 Strategic Operations Plan.pdf',
    targetClassification: 'SECRET',
    ip: '10.0.1.15',
    details: 'Viewed from KDT HQ network',
  },
  {
    id: 'a2',
    timestamp: '2026-04-06T16:15:00Z',
    user: 'Sarah Chen',
    userRole: 'HR Director',
    action: 'modified',
    target: 'Personnel Security Clearance Tracker.xlsx',
    targetClassification: 'SECRET',
    ip: '10.0.1.22',
    details: 'Updated 3 clearance records',
  },
  {
    id: 'a3',
    timestamp: '2026-04-06T15:45:00Z',
    user: 'Matthew McCalla',
    userRole: 'COO',
    action: 'downloaded',
    target: 'Quarterly Financial Report Q1-2026.xlsx',
    targetClassification: 'CONFIDENTIAL',
    ip: '10.0.1.10',
  },
  {
    id: 'a4',
    timestamp: '2026-04-06T15:30:00Z',
    user: 'James Rodriguez',
    userRole: 'Operations Lead',
    action: 'uploaded',
    target: 'Equipment Inventory - Q2 Audit.xlsx',
    targetClassification: 'CUI',
    ip: '10.0.2.8',
    details: 'New version uploaded (v2)',
  },
  {
    id: 'a5',
    timestamp: '2026-04-06T14:00:00Z',
    user: 'Michael Schulz',
    userRole: 'CEO',
    action: 'classified',
    target: 'Comms Plan - Operation Nightfall.pdf',
    targetClassification: 'SECRET',
    ip: '10.0.1.15',
    details: 'Classification upgraded from CONFIDENTIAL to SECRET',
  },
  {
    id: 'a6',
    timestamp: '2026-04-06T13:20:00Z',
    user: 'Sarah Chen',
    userRole: 'HR Director',
    action: 'shared',
    target: 'New Hire Training Schedule 2026.docx',
    targetClassification: 'UNCLASSIFIED',
    ip: '10.0.1.22',
    details: 'Shared with Training & SOPs team drive',
  },
  {
    id: 'a7',
    timestamp: '2026-04-06T12:10:00Z',
    user: 'Matthew McCalla',
    userRole: 'COO',
    action: 'signed',
    target: 'KDT Master Services Agreement - Template.docx',
    targetClassification: 'CONFIDENTIAL',
    ip: '10.0.1.10',
    details: 'Digital signature applied (SHA-256)',
  },
  {
    id: 'a8',
    timestamp: '2026-04-06T11:00:00Z',
    user: 'Michael Schulz',
    userRole: 'CEO',
    action: 'permission_changed',
    target: 'Intelligence Briefs',
    targetClassification: 'SECRET',
    ip: '10.0.1.15',
    details: 'Revoked access for external consultants',
  },
  {
    id: 'a9',
    timestamp: '2026-04-06T09:30:00Z',
    user: 'James Rodriguez',
    userRole: 'Operations Lead',
    action: 'modified',
    target: 'Vehicle Fleet Maintenance Log.xlsx',
    targetClassification: 'UNCLASSIFIED',
    ip: '10.0.2.8',
    details: 'Added March maintenance records',
  },
  {
    id: 'a10',
    timestamp: '2026-04-06T08:45:00Z',
    user: 'Michael Schulz',
    userRole: 'CEO',
    action: 'viewed',
    target: 'Threat Assessment Report - March 2026.pdf',
    targetClassification: 'SECRET',
    ip: '10.0.1.15',
  },
  {
    id: 'a11',
    timestamp: '2026-04-05T22:30:00Z',
    user: 'Michael Schulz',
    userRole: 'CEO',
    action: 'uploaded',
    target: 'Comms Plan - Operation Nightfall.pdf',
    targetClassification: 'SECRET',
    ip: '192.168.1.196',
    details: 'Uploaded from home network',
  },
  {
    id: 'a12',
    timestamp: '2026-04-05T17:00:00Z',
    user: 'Sarah Chen',
    userRole: 'HR Director',
    action: 'deleted',
    target: 'Outdated Policy Draft v1.docx',
    targetClassification: 'CUI',
    ip: '10.0.1.22',
    details: 'Moved to trash (30-day retention)',
  },
];

export const mockComplianceStats: ComplianceStat[] = [
  { label: 'Documents Classified', value: 156, total: 162, status: 'good' },
  { label: 'Encryption Compliance', value: 89, total: 94, status: 'good' },
  { label: 'Retention Policies Set', value: 78, total: 162, status: 'warning' },
  { label: 'Digital Signatures', value: 42, total: 67, status: 'warning' },
  { label: 'Access Reviews (30d)', value: 12, total: 15, status: 'good' },
  { label: 'DLP Violations (MTD)', value: 3, total: 0, status: 'critical' },
];

export const mockTeamDrives: TeamDrive[] = [
  {
    id: 'td1',
    name: 'Executive Leadership',
    description: 'C-suite strategic documents and board materials',
    memberCount: 4,
    fileCount: 89,
    classification: 'SECRET',
    icon: '⭐',
  },
  {
    id: 'td2',
    name: 'Field Operations',
    description: 'Operational plans, SOPs, and field reports',
    memberCount: 12,
    fileCount: 234,
    classification: 'CONFIDENTIAL',
    icon: '🎯',
  },
  {
    id: 'td3',
    name: 'Legal & Compliance',
    description: 'Contracts, agreements, and regulatory documents',
    memberCount: 6,
    fileCount: 156,
    classification: 'CONFIDENTIAL',
    icon: '⚖️',
  },
  {
    id: 'td4',
    name: 'Intelligence Division',
    description: 'Threat assessments, OSINT reports, and analysis',
    memberCount: 8,
    fileCount: 312,
    classification: 'SECRET',
    icon: '🔍',
  },
  {
    id: 'td5',
    name: 'Training & Development',
    description: 'Training materials, certifications, and course content',
    memberCount: 15,
    fileCount: 178,
    classification: 'CUI',
    icon: '📚',
  },
  {
    id: 'td6',
    name: 'Logistics & Supply',
    description: 'Inventory, procurement, and fleet management',
    memberCount: 9,
    fileCount: 145,
    classification: 'CUI',
    icon: '📦',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'approval',
    title: 'Approval Required',
    message: 'Comms Plan - Operation Nightfall.pdf requires your signature',
    timestamp: '2026-04-06T15:00:00Z',
    read: false,
  },
  {
    id: 'n2',
    type: 'compliance',
    title: 'DLP Alert',
    message: 'Personnel Clearance Tracker flagged for sensitive data patterns',
    timestamp: '2026-04-06T14:30:00Z',
    read: false,
  },
  {
    id: 'n3',
    type: 'share',
    title: 'New Shared Document',
    message: 'Matthew McCalla shared "Client Proposal - Nexus Corp" with you',
    timestamp: '2026-04-06T13:00:00Z',
    read: false,
  },
  {
    id: 'n4',
    type: 'system',
    title: 'Retention Notice',
    message: '5 documents approaching retention expiry in the next 30 days',
    timestamp: '2026-04-06T09:00:00Z',
    read: true,
  },
  {
    id: 'n5',
    type: 'compliance',
    title: 'Access Review Due',
    message: 'Quarterly access review for Intelligence Division is due April 15',
    timestamp: '2026-04-05T08:00:00Z',
    read: true,
  },
];

export const recentFiles = mockFiles.filter(f => f.type !== 'folder').slice(0, 8);
export const starredFiles = mockFiles.filter(f => f.starred);
export const folders = mockFiles.filter(f => f.type === 'folder');
export const documents = mockFiles.filter(f => f.type !== 'folder');
